version: '3'

services:
  v2ray-proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        TARGETPLATFORM: "linux/arm64"
        TAG: "v5.17.1"
    image: v2ray-proxy:v5.17.1
    container_name: v2ray-proxy
    ports:
      - "1080:1080"
    environment:
      - V2RAYSERVERIP=<IP>
      - V2RAYSERVERUID=<UID>
    volumes:
      - ./files/etc/v2ray:/etc/v2ray
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
        "
        sed -i -e "s/V2RAYSERVERIP/$$V2RAYSERVERIP/g" /etc/v2ray/config.json
        sed -i -e "s/V2RAYSERVERUID/$$V2RAYSERVERUID/g" /etc/v2ray/config.json
        /usr/bin/v2ray run -c /etc/v2ray/config.json
        "
    restart: unless-stopped
    networks:
      mikonet:
        ipv4_address: 192.168.0.2

  redsocks:
    build:
      context: ./redsocks-docker
      dockerfile: Dockerfile
    image: redsocks:latest
    container_name: redsocks
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    entrypoint: [ "/usr/local/bin/redsocks.sh", "192.168.0.2", "1080" ]
#    networks:
#      mikonet:
#        ipv4_address: 192.168.0.3

networks:
  mikonet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
